title: Meriah O'Neil
email: meriahoneil@gmail.com
description: Software Engineer in the Making

#About Section
skills:
- {name: Teaching, value: '4'}
- {name: UX Design, value: '7'}
- {name: Visual Design, value: '7'}
- {name: Communication, value: '8'}
- {name: Programming, value: '8'}
- {name: Organization, value: '9'}
- {name: Learning, value: '9'}
- {name: Planning, value: '10'}

#Portfolio Section
projects: 
- {name: ACTION Tutoring Program, folder: 'proj-1'}
- {name: Brick Breaker, folder: 'proj-2'}
